package es.uib.tfg.sports_league_backend.common

enum class ErrorCode {
    RESOURCE_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    INSTANTIATE_ONLY_CUSTOM_OR_ID_FIELD,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_ENCODING_FAILED,
    PASSWORDS_DONT_MATCH,
    PARTICIPANT_ALREADY_EXISTS,
    LEAGUE_ENDED,
    INSCRIPTIONS_CLOSED,
    CATEGORY_MISMATCH,
    SUBRESOURCE_MISMATCH,
    CREATE_RESOURCE_ERROR,
    REQUEST_ALREADY_RESOLVED,
    UNAUTHORIZED_ERROR,
    NOT_IN_A_TEAM,
    DORSAL_ALREADY_TAKEN
}