package es.uib.tfg.sports_league_backend.participant.domain.errors

sealed interface ParticipantJoinError
sealed interface ParticipantRetrieveError
sealed interface ParticipantUpdateError

object LeagueNotFound : ParticipantRetrieveError, ParticipantUpdateError
object UserNotFound : ParticipantRetrieveError
object AlreadyParticipant : ParticipantJoinError
object ParticipantNotFound : ParticipantRetrieveError, ParticipantUpdateError
object NotInATeam : ParticipantUpdateError
object UnauthorizedAction : ParticipantUpdateError
object DorsalAlreadyTaken : ParticipantUpdateError